# nfs_setup.yml
# Playbook para configurar servidor NFS en CentOS
- name: Configurar servidor NFS en CentOS
  hosts: centos # Grupo objetivo
  become: true
  collections:
    - ansible.posix

  vars:
    nfs_export_path: /var/nfs_shared
    nfs_export_line: "/var/nfs_shared *(rw,sync)"

  tasks:
    # Instala dependencias de NFS y el firewall
    - name: Instalar paquetes necesarios
      ansible.builtin.package:
        name:
          - nfs-utils
          - firewalld
        state: present

    # Activa el firewall y lo deja habilitado al arranque
    - name: Iniciar y habilitar firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    # Arranca y habilita el servicio del servidor NFS
    - name: Iniciar y habilitar nfs-server
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: true

    # Abre el puerto 2049/TCP (NFS)
    - name: Permitir puerto 2049/tcp en firewalld
      ansible.posix.firewalld:
        port: 2049/tcp
        state: enabled
        permanent: true
        immediate: true

    # Abre el puerto 2049/UDP (NFS)
    - name: Permitir puerto 2049/udp en firewalld
      ansible.posix.firewalld:
        port: 2049/udp
        state: enabled
        permanent: true
        immediate: true

    # Crea el directorio a exportar con dueño nobody:nobody y permisos 0777
    - name: Crear directorio exportado con permisos 0777
      ansible.builtin.file:
        path: "{{ nfs_export_path }}"
        state: directory
        owner: nobody
        group: nobody
        mode: "0777"

    # Declara el export en /etc/exports y notifica recarga si cambia
    - name: Asegurar línea en /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ nfs_export_line }}"
        create: true
        mode: "0644"
        state: present
        backup: true
      notify: Releer exports

  handlers:
    # Handler: recarga las exportaciones si la tarea anterior modificó /etc/exports
    - name: Releer exports
      ansible.builtin.command: exportfs -r
      changed_when: false
